name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: |
        sshpass -p ${{ secrets.PASSWORD }} ssh root@ivandev.ru
        ls
