name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: |
        sudo apt-get install sshpass
        sshpass -p ${{ secrets.PASSWORD }} ssh root@ivandev.ru
        ls

    - name: Run a one-line script
      run: echo Hello, world!
